name: Python application test with Github Actions

# Controls when the workflow will run
on: [push]
 

jobs:
  build:
  
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      - uses: actions/checkout@v2
      - name: Run a one-line script
        uses: actions/setup-python@v1
        with:
          python-version: 3.5

      - name: Install dependencies
        run: |
           make install
      - name: Lint with pylint
        run: |
          make lint
      - name: Test with pytest
        run: |
           make test
        
